import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
const roles=[['super-admin','Super Admin Dashboard'],['executive-management','Executive Dashboard'],['hr-manager','HR Dashboard'],['finance-manager','Finance Dashboard'],['operations-manager','Operations Dashboard'],['legal-manager','Legal Dashboard'],['standard-staff','Staff Dashboard']];
function Footer(){return <footer>© 2015–2026 Kutlwano & Associates (Pty) Ltd<br/><a href="/privacy">Privacy Policy</a> | <a href="/terms">Terms of Use</a></footer>}
function Shell({children,title}:{children:React.ReactNode;title:string}){return <main className="page"><section className="panel" aria-labelledby="page-title"><p className="eyebrow">KUTLWANO & ASSOCIATES (PTY) LTD</p><h1 id="page-title">{title}</h1>{children}</section><Footer/></main>}
function Field(p:React.InputHTMLAttributes<HTMLInputElement>&{label:string}){return <label>{p.label}<input {...p}/></label>}
function SignIn(){const[role,setRole]=useState('super-admin');return <Shell title="Secure Sign In"><form onSubmit={e=>{e.preventDefault(); location.href=`/dashboard/${role}`}}><Field label="Email address" type="email" autoComplete="email" required/><Field label="Password" type="password" autoComplete="current-password" required/><label>Role preview<select value={role} onChange={e=>setRole(e.target.value)}>{roles.map(([s,n])=><option key={s} value={s}>{n}</option>)}</select></label><button>Sign In</button><a href="/forgot-password">Forgot password?</a></form></Shell>}
function Forgot(){return <Shell title="Forgot Password"><form onSubmit={e=>{e.preventDefault(); location.href='/password-reset-sent'}}><p>Enter your staff email. If an account exists, a single-use reset link will be sent.</p><Field label="Email address" type="email" required/><button>Send Reset Email</button></form></Shell>}
function Sent(){return <Shell title="Password Reset Email Sent"><p>Check your inbox for a secure password reset link that expires in 60 minutes.</p><a className="button" href="/signin">Return to sign in</a></Shell>}
function NewPassword({confirm=false}:{confirm?:boolean}){return <Shell title={confirm?'Confirm New Password':'Create New Password'}><form onSubmit={e=>{e.preventDefault(); location.href=confirm?'/password-reset-success':'/confirm-new-password'}}><Field label="New password" type="password" autoComplete="new-password" required/><Field label="Confirm password" type="password" autoComplete="new-password" required/><p className="hint">Minimum 12 characters with uppercase, lowercase, number, and special character.</p><button>{confirm?'Confirm Password':'Continue'}</button></form></Shell>}
function Success(){return <Shell title="Password Reset Success"><p>Your password has been changed. You may now securely sign in.</p><a className="button" href="/signin">Sign In</a></Shell>}
function Dashboard(){const slug=location.pathname.split('/').pop()||'standard-staff'; const name=useMemo(()=>roles.find(r=>r[0]===slug)?.[1]??'Staff Dashboard',[slug]); return <Shell title={name}><p>Dashboard foundation placeholder. Business modules begin in Stage 2.</p><button onClick={()=>location.href='/signin'}>Secure Logout</button></Shell>}
function App(){const path=location.pathname; if(path==='/forgot-password')return <Forgot/>; if(path==='/password-reset-sent')return <Sent/>; if(path==='/create-new-password'||path.startsWith('/reset-password'))return <NewPassword/>; if(path==='/confirm-new-password')return <NewPassword confirm/>; if(path==='/password-reset-success')return <Success/>; if(path.startsWith('/dashboard/'))return <Dashboard/>; return <SignIn/>}
createRoot(document.getElementById('root')!).render(<App/>);
