import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

type RoleSlug = 'super-admin'|'executive-management'|'hr-manager'|'finance-manager'|'operations-manager'|'legal-manager'|'standard-staff';
const roles: Array<[RoleSlug,string,string]> = [
 ['super-admin','Super Admin Dashboard','Enterprise security, users, roles, and audit oversight.'],
 ['executive-management','Executive Dashboard','Strategic medico-legal portfolio overview placeholder.'],
 ['hr-manager','HR Dashboard','Staffing, compliance, and workforce placeholder.'],
 ['finance-manager','Finance Dashboard','Finance controls and billing placeholder.'],
 ['operations-manager','Operations Dashboard','Operational workflow placeholder.'],
 ['legal-manager','Legal Dashboard','Legal matters and compliance placeholder.'],
 ['standard-staff','Staff Dashboard','Assigned work and personal productivity placeholder.']
];
const API = import.meta.env.VITE_API_URL ?? 'http://localhost:10000';
async function api(path:string, init:RequestInit={}){ const csrf=localStorage.getItem('csrfToken'); const res=await fetch(`${API}${path}`,{credentials:'include',headers:{'Content-Type':'application/json',...(csrf?{'x-csrf-token':csrf}:{}),...init.headers},...init}); if(!res.ok) throw new Error((await res.json().catch(()=>({message:'Request failed'}))).message); return res.json(); }
function Footer(){return <footer aria-label="Legal footer">© 2015–2026 Kutlwano &amp; Associates (Pty) Ltd<br/><a href="/privacy">Privacy Policy</a> | <a href="/terms">Terms of Use</a></footer>}
function Shell({children,title,wide=false}:{children:React.ReactNode;title:string;wide?:boolean}){return <main className="page"><section className={`panel ${wide?'wide':''}`} aria-labelledby="page-title"><p className="eyebrow">KUTLWANO &amp; ASSOCIATES (PTY) LTD</p><h1 id="page-title">{title}</h1>{children}</section><Footer/></main>}
function Field(p:React.InputHTMLAttributes<HTMLInputElement>&{label:string;note?:string}){const id=p.id??p.name??p.label.replace(/\W+/g,'-').toLowerCase(); return <label htmlFor={id}>{p.label}<input id={id} {...p}/>{p.note&&<span className="hint">{p.note}</span>}</label>}
function SignIn(){const[error,setError]=useState(''); const[busy,setBusy]=useState(false); useEffect(()=>{api('/auth/csrf').then(r=>localStorage.setItem('csrfToken',r.csrfToken)).catch(()=>undefined)},[]); async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault(); setBusy(true); setError(''); const data=new FormData(e.currentTarget); try{const r=await api('/auth/sign-in',{method:'POST',body:JSON.stringify({email:data.get('email'),password:data.get('password')})}); location.href=`/dashboard/${r.user.role}`;}catch(err){setError(err instanceof Error?err.message:'Sign in failed')}finally{setBusy(false)}} return <Shell title="Secure Sign In"><form onSubmit={submit}><Field name="email" label="Email address" type="email" autoComplete="email" required/><Field name="password" label="Password" type="password" autoComplete="current-password" required/><button disabled={busy}>{busy?'Authenticating…':'Sign In'}</button>{error&&<p role="alert" className="error">{error}</p>}<a href="/forgot-password">Forgot password?</a></form></Shell>}
function Forgot(){const[done,setDone]=useState(false); async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault(); const data=new FormData(e.currentTarget); await api('/auth/forgot-password',{method:'POST',body:JSON.stringify({email:data.get('email')})}).catch(()=>undefined); setDone(true); setTimeout(()=>location.href='/password-reset-sent',300);} return <Shell title="Forgot Password">{done?<p role="status">Request received.</p>:<form onSubmit={submit}><p>Enter your staff email. If an account exists, a single-use reset link will be sent.</p><Field name="email" label="Email address" type="email" autoComplete="email" required/><button>Send Reset Email</button></form>}</Shell>}
function Sent(){return <Shell title="Password Reset Email Sent"><p>Check your inbox for a secure password reset link that expires in 60 minutes.</p><a className="button" href="/signin">Return to sign in</a></Shell>}
function NewPassword({confirm=false}:{confirm?:boolean}){const[error,setError]=useState(''); async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault(); const data=new FormData(e.currentTarget); const password=String(data.get('password')); const again=String(data.get('confirm')); if(password!==again){setError('Passwords do not match');return} if(!confirm){sessionStorage.setItem('pendingPassword',password); sessionStorage.setItem('pendingEndpoint',location.pathname==='/create-new-password'?'/auth/accept-invitation':'/auth/reset-password'); location.href='/confirm-new-password'+location.search; return} const token=new URLSearchParams(location.search).get('token')??''; const saved=sessionStorage.getItem('pendingPassword')??password; try{const endpoint=sessionStorage.getItem('pendingEndpoint')??'/auth/reset-password'; await api(endpoint,{method:'POST',body:JSON.stringify({token,password:saved})}); sessionStorage.removeItem('pendingPassword'); sessionStorage.removeItem('pendingEndpoint'); location.href='/password-reset-success';}catch(err){setError(err instanceof Error?err.message:'Reset failed')}} return <Shell title={confirm?'Confirm New Password':'Create New Password'}><form onSubmit={submit}><Field name="password" label="New password" type="password" autoComplete="new-password" required note="Minimum 12 characters with uppercase, lowercase, number, and special character."/><Field name="confirm" label="Confirm password" type="password" autoComplete="new-password" required/><button>{confirm?'Confirm Password':'Continue'}</button>{error&&<p role="alert" className="error">{error}</p>}</form></Shell>}
function Success(){return <Shell title="Password Reset Success"><p>Your password has been changed. You may now securely sign in.</p><a className="button" href="/signin">Sign In</a></Shell>}
function Dashboard(){const slug=(location.pathname.split('/').pop()||'standard-staff') as RoleSlug; const role=useMemo(()=>roles.find(r=>r[0]===slug)??roles[6],[slug]); async function logout(){await api('/auth/logout',{method:'POST'}).catch(()=>undefined); location.href='/signin'} return <Shell title={role[1]} wide><p>{role[2]}</p><div className="dashboard-grid">{roles.map(([s,n,d])=><article key={s}><h2>{n}</h2><p>{d}</p></article>)}</div><button onClick={logout}>Secure Logout</button></Shell>}
function Static({title}:{title:string}){return <Shell title={title}><p>This enterprise policy placeholder will be completed with approved legal content.</p><a className="button" href="/signin">Back</a></Shell>}
function App(){const path=location.pathname; if(path==='/forgot-password')return <Forgot/>; if(path==='/password-reset-sent')return <Sent/>; if(path==='/create-new-password'||path.startsWith('/reset-password'))return <NewPassword/>; if(path==='/confirm-new-password')return <NewPassword confirm/>; if(path==='/password-reset-success')return <Success/>; if(path.startsWith('/dashboard/'))return <Dashboard/>; if(path==='/privacy')return <Static title="Privacy Policy"/>; if(path==='/terms')return <Static title="Terms of Use"/>; return <SignIn/>}

createRoot(document.getElementById('root')!).render(<App/>);
