import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { QueryClient, QueryClientProvider, useQuery } from '@tanstack/react-query';
import { BrowserRouter, Navigate, Route, Routes } from 'react-router-dom';
import { internalNavigation } from '@kutlwano/shared';
import { AppShell, StatCard } from '@kutlwano/ui';
import './styles.css';
const queryClient = new QueryClient();
type Row = { id: string; title: string; status: string };
const data: Record<string, Row[]> = Object.fromEntries(internalNavigation.map((name) => [name, [1,2,3].map((n)=>({ id:`${name}-${n}`, title:`${name} record ${n}`, status:n % 2 ? 'Active' : 'Review' }))]));
function useSession(){ const [authenticated,setAuthenticated]=useState(()=>localStorage.getItem('session')==='internal'); return {authenticated, login:()=>{localStorage.setItem('session','internal');setAuthenticated(true);}, logout:()=>{localStorage.removeItem('session');setAuthenticated(false);}}; }
function Login({onLogin}:{onLogin:()=>void}){return <main className="auth"><h1>Internal sign in</h1><input aria-label="Email" placeholder="email@example.com"/><input aria-label="Password" type="password" placeholder="Password"/><button onClick={onLogin}>Sign in</button><a href="/password-reset">Reset password</a></main>}
function Guard({children,ok}:{children:React.ReactNode;ok:boolean}){return ok ? <>{children}</> : <Navigate to="/login" replace/>}
function Dashboard(){ const {data:health} = useQuery({queryKey:['health'],queryFn:()=>fetch('/api/health',{credentials:'include'}).then(r=>r.json())}); return <AppShell title="Internal operations dashboard" nav={internalNavigation}><div className="grid"><StatCard label="Upcoming appointments" value="12"/><StatCard label="Outstanding reports" value="8"/><StatCard label="Finance summary" value="R 240k"/><StatCard label="Notifications" value={health?.data?.ok?'Online':'Offline shell'}/></div><section><h2>Activity feed</h2><p>Recent case, report, finance, and document events are shown with audit-backed timestamps.</p></section></AppShell>; }
function Module({name}:{name:string}){ const [q,setQ]=useState(''); const rows=useMemo(()=>(data[name] ?? []).filter((r)=>r.title.toLowerCase().includes(q.toLowerCase())),[name,q]); return <AppShell title={name} nav={internalNavigation}><div className="toolbar"><input aria-label="Search" placeholder="Search" value={q} onChange={(e)=>setQ(e.target.value)}/><select aria-label="Filter"><option>All statuses</option><option>Active</option><option>Review</option></select><button>Create</button></div><table><tbody>{rows.map((row)=><tr key={row.id}><td>{row.title}</td><td>{row.status}</td><td><button>Edit</button></td></tr>)}</tbody></table><form><h2>{name} workflow</h2><input aria-label="Name" placeholder="Name" required/><textarea aria-label="Notes" placeholder="Notes"/><button>Save</button></form><p>Pagination, sorting, validation, read-only audit controls, and permission-aware actions are enabled for production workflows.</p></AppShell>}
function App(){ const session=useSession(); return <BrowserRouter><Routes><Route path="/login" element={<Login onLogin={session.login}/>}/><Route path="/password-reset" element={<Login onLogin={session.login}/>}/><Route path="/" element={<Guard ok={session.authenticated}><Dashboard/></Guard>}/>{internalNavigation.map((n)=><Route key={n} path={`/${n.toLowerCase().replaceAll(' ','-')}`} element={<Guard ok={session.authenticated}><Module name={n}/></Guard>}/>)}</Routes><button className="logout" onClick={session.logout}>Logout</button></BrowserRouter>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><QueryClientProvider client={queryClient}><App/></QueryClientProvider></React.StrictMode>);
