import { SignJWT, jwtVerify } from 'jose';
import type { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';
import { z } from 'zod';
import { config, secureCookie } from './config.js';
import { query } from './db.js';
import { emailTemplates } from './email.js';
import { fingerprint, hashPassword, secureToken, sha256, validatePassword, verifyPassword } from './security.js';
const accessKey = new TextEncoder().encode(config.JWT_ACCESS_SECRET);
const refreshKey = new TextEncoder().encode(config.JWT_REFRESH_SECRET);
const cookieOptions = { httpOnly:true, secure:secureCookie, sameSite:'strict' as const, path:'/' };
type UserRow={id:string;email:string;full_name:string;role_slug:string;password_hash:string|null;status:string;failed_login_count:number;locked_until:Date|null;force_password_reset:boolean};
async function audit(req:FastifyRequest,userId:string|null,action:string,result:'success'|'failure'|'blocked',metadata={}){ await query('insert into audit_logs(user_id,ip_address,device,action,result,metadata) values($1,$2,$3,$4,$5,$6)',[userId,req.ip,req.headers['user-agent']??'',action,result,metadata]); }
async function tokens(user:UserRow, req:FastifyRequest){ const access=await new SignJWT({role:user.role_slug,email:user.email}).setProtectedHeader({alg:'HS256'}).setSubject(user.id).setIssuedAt().setExpirationTime('15m').sign(accessKey); const refresh=secureToken(); const fp=fingerprint(req.headers['user-agent'],req.ip); await query('insert into sessions(user_id,refresh_token_hash,device_fingerprint,ip_address,user_agent,expires_at) values($1,$2,$3,$4,$5,now()+interval \'30 days\')',[user.id,sha256(refresh),fp,req.ip,req.headers['user-agent']??'']); return {access,refresh}; }
export async function requireAuth(req:FastifyRequest, reply:FastifyReply){ const token=req.cookies.access_token; if(!token) return reply.code(401).send({message:'Authentication required'}); try{ const {payload}=await jwtVerify(token,accessKey); req.user={id:String(payload.sub),role:String(payload.role),email:String(payload.email)}; }catch{ return reply.code(401).send({message:'Invalid session'}); } }
declare module 'fastify' { interface FastifyRequest { user?: { id:string; role:string; email:string } } }
export async function authRoutes(app:FastifyInstance){
 app.addHook('preHandler', async(req,reply)=>{ if(['POST','PUT','PATCH','DELETE'].includes(req.method) && !req.url.startsWith('/auth/sign-in') && !req.url.startsWith('/auth/refresh')){ const header=req.headers['x-csrf-token']; if(header !== req.cookies.csrf_token) return reply.code(403).send({message:'CSRF validation failed'}); }});
 app.get('/auth/csrf', async(_,reply)=>{ const token=secureToken(); reply.setCookie('csrf_token',token,{...cookieOptions,httpOnly:false}); return {csrfToken:token}; });
 app.post('/auth/sign-in', async(req,reply)=>{ const body=z.object({email:z.string().email(),password:z.string().min(1)}).parse(req.body); const {rows}=await query<UserRow>('select u.*, r.slug role_slug from users u join roles r on r.id=u.role_id where u.email=$1',[body.email]); const user=rows[0]; if(!user||!user.password_hash){ await audit(req,null,'failed_login','failure'); return reply.code(401).send({message:'Invalid credentials'}); } if(user.locked_until && new Date(user.locked_until)>new Date()){ await audit(req,user.id,'account_lock','blocked'); return reply.code(423).send({message:'Account locked'}); } if(!await verifyPassword(user.password_hash,body.password)){ const attempts=user.failed_login_count+1; await query('update users set failed_login_count=$1, locked_until=case when $1>=5 then now()+interval \'30 minutes\' else locked_until end where id=$2',[attempts,user.id]); if(attempts>=5) await emailTemplates.accountLocked(user.email); await audit(req,user.id,'failed_login','failure',{attempts}); return reply.code(401).send({message:'Invalid credentials'}); } const issued=await tokens(user,req); await query('update users set failed_login_count=0,last_login_at=now() where id=$1',[user.id]); await audit(req,user.id,'login','success'); reply.setCookie('access_token',issued.access,{...cookieOptions,maxAge:900}).setCookie('refresh_token',issued.refresh,{...cookieOptions,maxAge:2592000}); return {user:{email:user.email,name:user.full_name,role:user.role_slug},forcePasswordReset:user.force_password_reset}; });
 app.post('/auth/refresh', async(req,reply)=>{ const refresh=req.cookies.refresh_token; if(!refresh) return reply.code(401).send({message:'Missing refresh token'}); const {rows}=await query<UserRow & {session_id:string}>('select u.*, r.slug role_slug, s.id session_id from sessions s join users u on u.id=s.user_id join roles r on r.id=u.role_id where s.refresh_token_hash=$1 and s.revoked_at is null and s.expires_at>now()',[sha256(refresh)]); const user=rows[0]; if(!user) return reply.code(401).send({message:'Invalid refresh token'}); await query('update sessions set revoked_at=now(), rotated_at=now() where id=$1',[user.session_id]); const issued=await tokens(user,req); reply.setCookie('access_token',issued.access,{...cookieOptions,maxAge:900}).setCookie('refresh_token',issued.refresh,{...cookieOptions,maxAge:2592000}); return {ok:true}; });
 app.post('/auth/logout',{preHandler:requireAuth},async(req,reply)=>{ const refresh=req.cookies.refresh_token; if(refresh) await query('update sessions set revoked_at=now() where refresh_token_hash=$1',[sha256(refresh)]); await audit(req,req.user!.id,'logout','success'); reply.clearCookie('access_token',{path:'/'}).clearCookie('refresh_token',{path:'/'}); return {ok:true}; });
 app.post('/auth/forgot-password',async(req,reply)=>{ const body=z.object({email:z.string().email()}).parse(req.body); const {rows}=await query<{id:string;email:string}>('select id,email from users where email=$1',[body.email]); if(rows[0]){ const token=secureToken(); await query('insert into password_reset_tokens(user_id,token_hash,expires_at) values($1,$2,now()+interval \'60 minutes\')',[rows[0].id,sha256(token)]); await emailTemplates.passwordReset(rows[0].email,`${config.FRONTEND_URL}/reset-password?token=${token}`); await audit(req,rows[0].id,'password_reset','success'); } return {ok:true}; });
 app.post('/auth/reset-password',async(req,reply)=>{ const body=z.object({token:z.string(),password:z.string()}).parse(req.body); const errors=validatePassword(body.password); if(errors.length) return reply.code(400).send({errors}); const {rows}=await query<{user_id:string;email:string}>('select t.user_id,u.email from password_reset_tokens t join users u on u.id=t.user_id where t.token_hash=$1 and t.used_at is null and t.expires_at>now()',[sha256(body.token)]); const row=rows[0]; if(!row) return reply.code(400).send({message:'Invalid or expired token'}); const passwordHash=await hashPassword(body.password); await query('update users set password_hash=$1,status=\'active\',force_password_reset=false,password_changed_at=now() where id=$2',[passwordHash,row.user_id]); await query('insert into password_history(user_id,password_hash) values($1,$2)',[row.user_id,passwordHash]); await query('update password_reset_tokens set used_at=now() where token_hash=$1',[sha256(body.token)]); await emailTemplates.passwordChanged(row.email); await audit(req,row.user_id,'password_change','success'); return {ok:true}; });

 app.post('/staff/invitations',{preHandler:requireAuth},async(req,reply)=>{ if(req.user!.role!=='super-admin') return reply.code(403).send({message:'Super Admin access required'}); const body=z.object({email:z.string().email(),fullName:z.string().min(2),roleSlug:z.string().min(2)}).parse(req.body); const role=await query<{id:string}>('select id from roles where slug=$1',[body.roleSlug]); if(!role.rows[0]) return reply.code(400).send({message:'Unknown role'}); const created=await query<{id:string}>("insert into users(role_id,email,full_name,status,created_by,force_password_reset) values($1,$2,$3,'invited',$4,true) returning id",[role.rows[0].id,body.email,body.fullName,req.user!.id]); const token=secureToken(); await query("insert into email_verifications(user_id,token_hash,purpose,expires_at) values($1,$2,'staff_invitation',now()+interval '60 minutes')",[created.rows[0].id,sha256(token)]); await emailTemplates.invitation(body.email,`${config.FRONTEND_URL}/create-new-password?token=${token}`); await audit(req,created.rows[0].id,'staff_invitation','success',{role:body.roleSlug}); return reply.code(201).send({ok:true}); });
 app.post('/sessions/revoke-all',{preHandler:requireAuth},async(req)=>{ await query('update sessions set revoked_at=now() where user_id=$1 and revoked_at is null',[req.user!.id]); await audit(req,req.user!.id,'session_revoke','success',{scope:'global'}); return {ok:true}; });
 app.get('/me',{preHandler:requireAuth},async(req)=>({user:req.user}));
}
