import Fastify from 'fastify';
import cookie from '@fastify/cookie';
import cors from '@fastify/cors';
import helmet from '@fastify/helmet';
import rateLimit from '@fastify/rate-limit';
import { randomUUID } from 'node:crypto';
import { z } from 'zod';
import { cookieNames } from '@kutlwano/security';
import { query } from './db.js';
import { env } from './config.js';
import { signAccessToken, signRefreshToken } from './auth.js';
const app = Fastify({ logger: true, genReqId: () => randomUUID() });
await app.register(helmet);
await app.register(rateLimit, { max: 100, timeWindow: '1 minute' });
await app.register(cookie, { secret: env.COOKIE_SECRET });
await app.register(cors, { credentials: true, origin: [env.CORS_INTERNAL_ORIGIN, env.CORS_EXTERNAL_ORIGIN] });
app.get('/health', async (request) => ({ data: { ok: true, databaseFirst: true }, requestId: request.id }));
app.post('/auth/login', async (request, reply) => { const body = z.object({ email:z.string().email(), password:z.string().min(8), actorType:z.enum(['internal','external']) }).parse(request.body); const rows = await query<{user_id:string; roles:string[]; permissions:string[]}>('select user_id, roles, permissions from security.authenticate_user($1, $2, $3)', [body.email, body.password, body.actorType]); const user = rows[0]; if(!user) return reply.code(401).send({ error:'Invalid credentials' }); const session = { userId:user.user_id, actorType:body.actorType, roles:user.roles, permissions:user.permissions, mfaVerified:false }; reply.setCookie(cookieNames.access, await signAccessToken(session), { httpOnly:true, secure:true, sameSite:'strict', path:'/' }); reply.setCookie(cookieNames.refresh, await signRefreshToken(session, randomUUID()), { httpOnly:true, secure:true, sameSite:'strict', path:'/auth/refresh' }); return { data: session, requestId: request.id }; });
app.get('/master-files', async (request) => ({ data: await query('select * from dashboard.v_master_file_dashboard limit $1', [100]), requestId: request.id }));
app.get('/documents/:id', async (request) => { const params = z.object({ id:z.string().uuid() }).parse(request.params); return { data: await query('select * from documents.documents where document_id = $1', [params.id]), requestId: request.id }; });
app.get('/audit', async (request) => ({ data: await query('select * from audit.audit_log order by created_at desc limit $1', [200]), requestId: request.id }));
await app.listen({ host: '0.0.0.0', port: env.API_PORT });
