import Fastify from 'fastify';
import cookie from '@fastify/cookie';
import cors from '@fastify/cors';
import helmet from '@fastify/helmet';
import rateLimit from '@fastify/rate-limit';
import { config } from './config.js';
import { authRoutes, requireAuth } from './auth.js';
const app=Fastify({logger:true,trustProxy:true});
await app.register(helmet,{contentSecurityPolicy:{directives:{defaultSrc:["'self'"],scriptSrc:["'self'"],styleSrc:["'self'","'unsafe-inline'"],imgSrc:["'self'","data:"],connectSrc:["'self'",config.FRONTEND_URL]}}});
await app.register(cors,{origin:config.FRONTEND_URL,credentials:true});
await app.register(cookie,{secret:config.COOKIE_SECRET});
await app.register(rateLimit,{max:100,timeWindow:'1 minute'});
app.addHook('onSend',async(_req,reply)=>{reply.header('Strict-Transport-Security','max-age=63072000; includeSubDomains; preload').header('Referrer-Policy','no-referrer').header('Permissions-Policy','camera=(), microphone=(), geolocation=()').header('X-Content-Type-Options','nosniff');});
await app.register(authRoutes);
app.get('/health',async()=>({ok:true,service:'kutlwano-api'}));
app.get('/dashboard/:role',{preHandler:requireAuth},async(req)=>({dashboard:(req.params as {role:string}).role}));
await app.listen({port:config.PORT,host:'0.0.0.0'});
